-- TABLA 1: CENTROS_FORENSES (Relación 1 a N con MUESTRAS_FORENSES) 
CREATE TABLE CENTROS_FORENSES ( 
    ID SERIAL PRIMARY KEY, 
    NOMBRE VARCHAR(100) NOT NULL, 
    PAIS VARCHAR(100), 
    NIVEL_SEGURIDAD INT, 
    AUTOR_EXAMEN VARCHAR(150) NOT NULL 
); 

 -- TABLA 2: MUESTRAS_FORENSES
CREATE TABLE MUESTRAS_FORENSES ( 
    ID SERIAL PRIMARY KEY, 
    CODIGO_CASO INT NOT NULL, 
    TIPO_MUESTRA VARCHAR(50), 
    FECHA_RECOGIDA DATE, 
    ESTADO_CUSTODIA VARCHAR(50), 
    CENTRO_ID INT, 
    AUTOR_EXAMEN VARCHAR(150) NOT NULL, 
    CONSTRAINT FK_CENTROS_FORENSES FOREIGN KEY (CENTRO_ID) REFERENCES CENTROS_FORENSES(ID) 
); 

 -- TABLA 3: INFORMES_FORENSES (Relación 1 a 1 con MUESTRAS_FORENSES) 
CREATE TABLE INFORMES_FORENSES ( 
    ID SERIAL PRIMARY KEY, 
    ADN_POSITIVO BOOLEAN, 
    NIVEL_RIESGO VARCHAR(50), 
    CONCLUSION  VARCHAR(200), 
    MUESTRA_ID INT UNIQUE, 
    AUTOR_EXAMEN VARCHAR(150) NOT NULL, 
    CONSTRAINT FK_MUESTRAS_FORENSES FOREIGN KEY (MUESTRA_ID) REFERENCES MUESTRAS_FORENSES(ID) 
);