INSERT INTO CENTROS_FORENSES (NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN) VALUES  
('CENTRO_1', 'USA', '5', 'LIDIA_ROJO_DAM2'), 
('CENTRO_2', 'España', '9', 'LIDIA_ROJO_DAM2'), 
('CENTRO_3', 'Japón', '10', 'LIDIA_ROJO_DAM2'), 
('CENTRO_4', 'Rusia', '9', 'LIDIA_ROJO_DAM2'), 
('CENTRO_5', 'India', '7', 'LIDIA_ROJO_DAM2'); 

INSERT INTO MUESTRAS_FORENSES (CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, CENTRO_ID, AUTOR_EXAMEN) VALUES  
('00000001', 'SANGRE', '1990-04-24', 'GUARDADA', 1, 'LIDIA_ROJO_DAM2'), 
('00000002', 'LIQUIDO_CEFALORAQUIDEO', '2011-10-21', 'ENVIADA', 2, 'LIDIA_ROJO_DAM2'), 
('00000003', 'SANGRE', '1957-10-04', 'GUARDADA', 3, 'LIDIA_ROJO_DAM2'), 
('00000004', 'PULMON', '2008-10-22', 'ANALIZADA', 4, 'LIDIA_ROJO_DAM2'), 
('00000005 ', 'HIGADO', '2021-12-25', 'PERDIDA', 5, 'LIDIA_ROJO_DAM2'); 

INSERT INTO INFORMES_FORENSES (ADN_POSITIVO, NIVEL_RIESGO, CONCLUSION, MUESTRA_ID, AUTOR_EXAMEN) VALUES  
(TRUE, 20, 'La muestra no presenta signos de peligrosidad', 1, 'LIDIA_ROJO_DAM2'), 
(TRUE, 92, 'Muestra numero 2 del centro 2', 2, 'LIDIA_ROJO_DAM2'), 
(FALSE, 50, 'Muestra guardada por el laboratorio segundo de japon', 3, 'LIDIA_ROJO_DAM2'), 
(TRUE, 30, 'Es segura la muestra', 4, 'LIDIA_ROJO_DAM2'), 
(FALSE, 80, 'No tocar bajo ningun concepto', 5, 'LIDIA_ROJO_DAM2');