SELECT * FROM MUESTRAS_FORENSES ORDER BY ID

SELECT * FROM MUESTRAS_FORENSES WHERE ID = ?

INSERT INTO MUESTRAS_FORENSES (CODIGO_CASO, TIPO_MUESTRA, FECHA_RECOGIDA, ESTADO_CUSTODIA, CENTRO_ID, AUTOR_EXAMEN) VALUES (?, ?, ?, ?, ?, 'LIDIA_ROJO_DAM2')

DELETE FROM MUESTRAS_FORENSES WHERE ID = ?

SELECT * FROM MUESTRAS_FORENSES M INNER JOIN CENTROS_FORENSES C ON M.CENTRO_ID = C.ID WHERE C.NOMBRE = ? ;

SELECT M.ID, M.CODIGO_CASO, M.TIPO_MUESTRA, M.FECHA_RECOGIDA, M.ESTADO_CUSTODIA, I.ID AS INF_ID, I.ADN_POSITIVO, I.NIVEL_RIESGO, I.CONCLUSION 
FROM MUESTRAS_FORENSES M 
INNER JOIN CENTROS_FORENSES C ON M.CENTRO_ID = C.ID 
INNER JOIN INFORMES_FORENSES I ON M.ID = I.MUESTRA_ID 
WHERE I.ADN_POSITIVO = TRUE AND I.NIVEL_RIESGO > 90 AND C.PAIS = 'ESPAÑA'





SELECT * FROM CENTROS_FORENSES ORDER BY ID

SELECT * FROM CENTROS_FORENSES WHERE ID = ?

INSERT INTO CENTROS_FORENSES (NOMBRE, PAIS, NIVEL_SEGURIDAD, AUTOR_EXAMEN) VALUES (?, ?, ?, 'LIDIA_ROJO_DAM2')

DELETE FROM CENTROS_FORENSES WHERE ID = ?
